### ISSUE TITLE
训练好模型后evaluate出现问题

### ISSUE THREAD

**Issue by sakura-iv** [lmbxmu/HRankPlus#1]
作者你好，我是用的HRank-master对ResNet56做了训练，compress rate采用的 [0.1]+[0.60]*35+[0.0]*2+[0.6]*6+[0.4]*3+[0.1]+[0.4]+[0.1]+[0.4]+[0.1]+[0.4]+[0.1]+[0.4] ， 训练后我发现HRank没有给出evaluate的步骤，于是用HRankPlus中的evaluate_cifar进行test ，却报了如下错误：

> Traceback (most recent call last):
>   File "evaluate_cifar.py", line 801, in <module>
>     main()
>   File "evaluate_cifar.py", line 615, in main
>     model.load_state_dict(checkpoint['state_dict'])
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for ResNet:
>         Missing key(s) in state_dict: "total_ops", "total_params", "layers.total_ops", "layers.total_params", "layer1.total_ops", "layer1.total_params", "layer1.0.total_ops", "layer1.0.total_params", "layer1.0.shortcut.total_ops", "layer1.0.shortcut.total_params", "layer1.1.total_ops", "layer1.1.total_params", "layer1.1.shortcut.total_ops", "layer1.1.shortcut.total_params", "layer1.2.total_ops", "layer1.2.total_params", "layer1.2.shortcut.total_ops", "layer1.2.shortcut.total_params", "layer1.3.total_ops", "layer1.3.total_params", "layer1.3.shortcut.total_ops", "layer1.3.shortcut.total_params", "layer1.4.total_ops", "layer1.4.total_params", "layer1.4.shortcut.total_ops", "layer1.4.shortcut.total_params", "layer1.5.total_ops", "layer1.5.total_params", "layer1.5.shortcut.total_ops", "layer1.5.shortcut.total_params", "layer1.6.total_ops", "layer1.6.total_params", "layer1.6.shortcut.total_ops", "layer1.6.shortcut.total_params", "layer1.7.total_ops", "layer1.7.total_params", "layer1.7.shortcut.total_ops", "layer1.7.shortcut.total_params", "layer1.8.total_ops", "layer1.8.total_params", "layer1.8.shortcut.total_ops", "layer1.8.shortcut.total_params", "layer2.total_ops", "layer2.total_params", "layer2.0.total_ops", "layer2.0.total_params", "layer2.0.shortcut.total_ops", "layer2.0.shortcut.total_params", "layer2.1.total_ops", "layer2.1.total_params", "layer2.1.shortcut.total_ops", "layer2.1.shortcut.total_params", "layer2.2.total_ops", "layer2.2.total_params", "layer2.2.shortcut.total_ops", "layer2.2.shortcut.total_params", "layer2.3.total_ops", "layer2.3.total_params", "layer2.3.shortcut.total_ops", "layer2.3.shortcut.total_params", "layer2.4.total_ops", "layer2.4.total_params", "layer2.4.shortcut.total_ops", "layer2.4.shortcut.total_params", "layer2.5.total_ops", "layer2.5.total_params", "layer2.5.shortcut.total_ops", "layer2.5.shortcut.total_params", "layer2.6.total_ops", "layer2.6.total_params", "layer2.6.shortcut.total_ops", "layer2.6.shortcut.total_params", "layer2.7.total_ops", "layer2.7.total_params", "layer2.7.shortcut.total_ops", "layer2.7.shortcut.total_params", "layer2.8.total_ops", "layer2.8.total_params", "layer2.8.shortcut.total_ops", "layer2.8.shortcut.total_params", "layer3.total_ops", "layer3.total_params", "layer3.0.total_ops", "layer3.0.total_params", "layer3.0.shortcut.total_ops", "layer3.0.shortcut.total_params", "layer3.1.total_ops", "layer3.1.total_params", "layer3.1.shortcut.total_ops", "layer3.1.shortcut.total_params", "layer3.2.total_ops", "layer3.2.total_params", "layer3.2.shortcut.total_ops", "layer3.2.shortcut.total_params", "layer3.3.total_ops", "layer3.3.total_params", "layer3.3.shortcut.total_ops", "layer3.3.shortcut.total_params", "layer3.4.total_ops", "layer3.4.total_params", "layer3.4.shortcut.total_ops", "layer3.4.shortcut.total_params", "layer3.5.total_ops", "layer3.5.total_params", "layer3.5.shortcut.total_ops", "layer3.5.shortcut.total_params", "layer3.6.total_ops", "layer3.6.total_params", "layer3.6.shortcut.total_ops", "layer3.6.shortcut.total_params", "layer3.7.total_ops", "layer3.7.total_params", "layer3.7.shortcut.total_ops", "layer3.7.shortcut.total_params", "layer3.8.total_ops", "layer3.8.total_params", "layer3.8.shortcut.total_ops", "layer3.8.shortcut.total_params".
>         size mismatch for conv1.weight: copying a param with shape torch.Size([16, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([14, 3, 3, 3]).
>         size mismatch for bn1.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([14]).
>         size mismatch for bn1.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([14]).
>         size mismatch for bn1.running_mean: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([14]).
>         size mismatch for bn1.running_var: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([14]).
>         size mismatch for layer1.0.conv1.weight: copying a param with shape torch.Size([16, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([6, 14, 3, 3]).
>         size mismatch for layer1.0.bn1.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([6]).
>         size mismatch for layer1.0.bn1.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([6]).
>         size mismatch for layer1.0.bn1.running_mean: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([6]).
>         size mismatch for layer1.0.bn1.running_var: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([6]).
>         size mismatch for layer1.0.conv2.weight: copying a param with shape torch.Size([16, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([6, 6, 3, 3]).
>         size mismatch for layer1.0.bn2.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([6]).
>         size mismatch for layer1.0.bn2.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([6]).
>         size mismatch for layer1.0.bn2.running_mean: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([6]).
>         size mismatch for layer1.0.bn2.running_var: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([6]).
>         size mismatch for layer1.1.conv1.weight: copying a param with shape torch.Size([16, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([6, 6, 3, 3]).
>         size mismatch for layer1.1.bn1.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([6]).
>         size mismatch for layer1.1.bn1.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([6]).
>         size mismatch for layer1.1.bn1.running_mean: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([6]).
>         size mismatch for layer1.1.bn1.running_var: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([6]).
>         size mismatch for layer1.1.conv2.weight: copying a param with shape torch.Size([16, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([6, 6, 3, 3]).
>         size mismatch for layer1.1.bn2.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([6]).
>         size mismatch for layer1.1.bn2.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([6]).

这里只截取了一部分，后面报错全是size mismatch，这里的test_model_dir我选择的是resnet_56_conv55.pt，您在HRank-master也说选取最大的pt文件就是最终训练好的模型。但是看起来这个训练好的模型保存的参数貌似还是prune以前的shape？请问如何处理呢？非常感谢！

**Comment by lmbxmu** [comment]
HRank里的代码我们采用模拟剪枝的方式，即将剪掉的filter采取置0的方式而非直接移除，所以在代码上shape和pruning之前的是一样的.

HRankPlus我们采用了真实剪枝方式，即剪掉的filter直接移除，所以shape会和pruning之前的不同

因此，你在HRank跑的模型用Plus的代码进行inference会出现shape inconsistency的情况

我稍后会让人添加下HRank test的指令。

另外，建议你跑HRankPlus的代码, 这个是全局剪枝然后一个end-to-end fine-tuning，效果更高性能也更好; HRank我采用layer-wise的剪枝和fine-tuning,训练成本太高不推荐。

**Comment by lmbxmu** [comment]
HRank里的代码我们采用模拟剪枝的方式，即将剪掉的filter采取置0的方式而非直接移除，所以在代码上shape和pruning之前的是一样的.

HRankPlus我们采用了真实剪枝方式，即剪掉的filter直接移除，所以shape会和pruning之前的不同

因此，你在HRank跑的模型用Plus的代码进行inference会出现shape inconsistency的情况

我稍后会让人添加下HRank test的指令。

另外，建议你跑HRankPlus的代码, 这个是全局剪枝然后一个end-to-end fine-tuning，效果更高性能也更好, 剪完的pt文件就是小型化的网络; HRank我采用layer-wise的剪枝和fine-tuning,训练成本太高，而且剪完的模型size和原来也是一样的，不推荐。

**Comment by sakura-iv** [comment]
好的好的，明白了，非常感谢！^-^
