### ISSUE TITLE
The reason that the output channels of last block in ResNet not effected by compression rate ?

### ISSUE THREAD

**Issue by MJ0210028** [lmbxmu/HRankPlus#2]
Hi! Thanks for sharing the amazing work! 
When I was digging into the code, I found out that when you are calculating adapt_channel, the number of output channels of last block is always set to 64 (without considering the compression rate), 
Is there a reason for this ? 
https://github.com/lmbxmu/HRankPlus/blob/49e7bc95a05e941f0338ec6f3b9667bd49a932b8/models/cifar10/resnet.py#L18

**Comment by lmbxmu** [comment]
> Hi! Thanks for sharing the amazing work!
> When I was digging into the code, I found out that when you are calculating adapt_channel, the number of output channels of last block is always set to 64 (without considering the compression rate),
> Is there a reason for this ?
> https://github.com/lmbxmu/HRankPlus/blob/49e7bc95a05e941f0338ec6f3b9667bd49a932b8/models/cifar10/resnet.py#L18

It is just a pruning strategy that we consider keeping the fc layer unchanged. Of course, you can choose to prune it as well.

**Comment by MJ0210028** [comment]
Got it. Thanks for the quick reply!
